public enum Piece {
    ROI_BLANC,
    DAME_BLANC,
    FOUS_BLANC,
    CAVALIERS_BLANC,
    TOURS_BLANC,
    PIONS_BLANC,
    ROI_NOIR,
    DAME_NOIR,
    FOUS_NOIR,
    CAVALIERS_NOIR,
    TOURS_NOIR,
    PIONS_NOIR
}
